region         = "${region}"
bucket         = "${bucket}"
key            = "${terraform_state_file}"
dynamodb_table = "${dynamodb_table}"
profile        = "${profile}"
role_arn       = "${role_arn}"
encrypt        = "${encrypt}"
